main: Plugin.CustomShops
name: CustomShops
version: 1.0
author: SolarRabbit
api-version: 1.16

commands:
    removeshop:
        description: Removes a shop.
    newshop:
        description: Creates a new shop.
    setcrate:
        description: Set the chest for crate.
        permission: customshop.admin
        permission-message: You do not have permission to use this command.
    gettotal:
        description: Returns the total number of custom shops owned.

permissions:
    customshop.admin:
        description: User able to set the location of the crate.
        default: op
