############################################################
# +------------------------------------------------------+ #
# |                  Main Configurations                 | #
# +------------------------------------------------------+ #
############################################################

# How many custom shops can a player own?
max-shops: 5

############################################################
# +------------------------------------------------------+ #
# |                      Model Data                      | #
# +------------------------------------------------------+ #
#                                                          #
#   Deconflict your custom model data here. Make sure      #
#   that the data here correctly corresponds to the data   #
#   in the resource pack.                                  #
#                                                          #
############################################################

defaults:
    vending-machine: 100000

vending-machine:
    wooden:
        name: §r§6Wooden Vending Machine
        model-data: 100001
    stone:
        name: §r§6Stone Vending Machine
        model-data: 100002
    nether:
        name: §r§6Nether Vending Machine
        model-data: 100003
    sand:
        name: §r§6Sand Vending Machine
        model-data: 100004
