############################################################
# +------------------------------------------------------+ #
# |                  Main Configurations                 | #
# +------------------------------------------------------+ #
############################################################

# How many custom shops can a player own?
max-shops: 5

# Unlock all designs for all players? (`/customshop lockall <player>` command will have no effect if enabled)
unlock-all: true

############################################################
# +------------------------------------------------------+ #
# |                      Crate Key                       | #
# +------------------------------------------------------+ #
############################################################

# Display name of crate key.
crate-key-name: §r§b[§5§lCustom Shop Crate Key§b]

# Item lore for crate keys.
crate-key-lore:
    - §9Use key on Custom Shop Crate!

############################################################
# +------------------------------------------------------+ #
# |                Messages (Transactions)               | #
# +------------------------------------------------------+ #
############################################################

# Placeholders:
# Customer      %customer%      Username of the customer, either purchasing or selling items to the shop
# Owner         %owner%         Username of the owner of the shop
# Total         %total%         Total amount of money involved in the transaction
# Item          %item%          Display name of the item, or its material type if display name is absent
# Amount        %amount%        Amount of items purchased/sold to the shop

# Message to shop owner when shop owner successfully sold to customer.
customer-buy-success-owner: §c{%customer%} bought {%amount%}x{%item%}§c from you for {%total%}.

# Message to customer when customer successfully purchased item from shop.
customer-buy-success-customer: §aSuccessfully purchased {%amount%}x{%item%}§a for {%total%}.

# Message to customer when customer failed to purchase item from shop due to insufficient money.
customer-buy-fail-money: §cYou need at least {%total%} to make the purchase!

# Message to customer when customer failed to purchase item from shop due to insufficient space.
customer-buy-fail-space: §cYou do not have enough space in your inventory!

# Message to customer when customer failed to purchase item from shop due to insufficient items in shop.
customer-buy-fail-item: §cShop does not have the specified amount of the selected item!

# Message to shop owner when shop owner successfully bought from customer.
customer-sell-success-owner: §a{%customer%} sold {%amount%}x{%item%}§a to you for {%total%}.

# Message to customer when customer successfully sold item to shop.
customer-sell-success-customer: §aSuccessfully sold {%amount%}x{%item%}§a for {%total%}.

# Message to customer when customer failed to sell item to shop due to owner's insufficient money.
customer-sell-fail-money: §c{%owner%} does not have enough money!

# Message to customer when customer failed to sell item to shop due to insufficient items.
customer-sell-fail-item: §cYou do not have the specified amount of the specified item!

############################################################
# +------------------------------------------------------+ #
# |                      Model Data                      | #
# +------------------------------------------------------+ #
#                                                          #
#   Deconflict your custom model data here. Make sure      #
#   that the data here correctly corresponds to the data   #
#   in the resource pack. Keep custom model data to no     #
#   than 6 digits. DO NOT change model data once players   #
#   start unlocking shops!                                 #
#                                                          #
############################################################

defaults:
    vending-machine: 100
    briefcase: 200

vending-machine:
    wooden:
        name: §r§6Wooden Vending Machine
        model-data: 101
    stone:
        name: §r§6Stone Vending Machine
        model-data: 102
    nether:
        name: §r§6Nether Vending Machine
        model-data: 103
    sand:
        name: §r§6Sand Vending Machine
        model-data: 104
    prismarine:
        name: §r§6Prismarine Vending Machine
        model-data: 105
    ice:
        name: §r§6Ice Vending Machine
        model-data: 106
    blackstone:
        name: §r§6Blackstone Vending Machine
        model-data: 107
    copper:
        name: §r§6Copper Vending Machine
        model-data: 108
    amethyst:
        name: §r§6Amethyst Vending Machine
        model-data: 109

briefcase:
    wooden:
        name: §r§6Wooden Newt's Briefcase
        model-data: 201
    stone:
        name: §r§6Stone Newt's Briefcase
        model-data: 202
