main: plugin.CustomShop
name: CustomShop
version: 1.0
author: SolarRabbit
api-version: 1.16

commands:
    removeshop:
        alias: [rm]
        description: Removes a shop.
    newshop:
        alias: [ns]
        description: Creates a new shop.
    gettotal:
        description: Returns the total number of custom shops owned.
    setcrate:
        description: Set the chest for crate.
        permission: customshop.setcrate
        permission-message: You do not have permission to use this command.
    givekey:
        alias: [givecustomshopkey]
        description: Gives custom shop crate keys to the specified player.
        permission: customshop.givekey
        permission-message: You do not have permission to use this command.
        usage: /<command> <player> <amount>
    lockall:
        description: Locks all custom shops of the specified player.
        permission: customshop.lockall
        permission-message: You do not have permission to use this command.
        usage: /<command> <player>

permissions:
    customshop.setcrate:
        description: User able to set the location of the crate.
        default: op
    customshop.givekey:
        description: User able to give custom shop crate keys to players.
        default: op
    customshop.lockall:
        description: User able to lock all custom shops of a player.
        default: op
    customshop.admin:
        description: User able to perform all commands.
        default: op
        children:
            customshop.setcrate: true
            customshop.givekey: true
            customshop.lockall: true
