main: com.paratopiamc.customshop.plugin.CustomShop
name: CustomShop
version: 1.3
author: SolarRabbit
api-version: 1.14

depend: [Vault]
softdepend: [Towny, WorldGuard, GriefPrevention, Lands, ItemsAdder, ProtocolLib]

commands:
    customshop:
        aliases: [cs]

permissions:
    customshop.createshop:
        description: User able to create non-admin shops.
        default: true
    customshop.removeshop.break:
        description: User able to remove shops by breaking blocks.
        default: true
    customshop.removeshop.command:
        description: User able to remove shops through command. Briefcases removed via command will not drop any items.
        default: op
    customshop.lockall:
        description: User able to lock all custom shops of a player.
        default: op
    customshop.setcount:
        description: User able to set the shop count of a player.
        default: op
    customshop.reload:
        description: User able to reload configuration of the plugin.
        default: op
    customshop.admin:
        description: User able to perform all commands and full access to admin shops.
        default: op
        children:
            customshop.removeshop.command: true
            customshop.lockall: true
            customshop.setcount: true
            customshop.reload: true
