############################################################
# +------------------------------------------------------+ #
# |                  Main Configurations                 | #
# +------------------------------------------------------+ #
############################################################

# How many custom shops can a player own?
max-shops: 3

# Unlock all designs for all players? (`/customshop lockall <player>` command will have no effect if enabled)
unlock-all: true

# Language to be used for the server (Currently available: english, chinese, italian, german)
language: english

# Set this to true if the currency's unit that you are using is integer (e.g. emeralds)
round-down-price: false

# Maximum price that players can set for items (DO NOT set it arbitrarily large, though billions are tested fine too)
max-price: 5000000.00

############################################################
# +------------------------------------------------------+ #
# |                      Model Data                      | #
# +------------------------------------------------------+ #
#                                                          #
#   Deconflict your custom model data here. Make sure      #
#   that the data here correctly corresponds to the data   #
#   in the resource pack. You can choose to delete/rename  #
#   sub-sections (e.g. "wooden" section under              #
#   "vending-machine") if you do not want them in your     #
#   server.                                                #
#                                                          #
#   WARNING: DO NOT remove/rename the main sections        #
#   (e.g. "vending-machine", "briefcase" and anything      #
#   under "default")!                                      #
#                                                          #
#   WARNING: DO NOT change model data once players         #
#   start unlocking or creating shops!                     #
#                                                          #
#   NOTE: You can safely ignore the custom model data if   #
#   you have ItemsAdder installed.                         #
#                                                          #
############################################################

defaults:
    vending-machine: 100
    briefcase: 200

vending-machine:
    wooden:
        name: §6Wooden Vending Machine
        model-data: 101
    stone:
        name: §6Stone Vending Machine
        model-data: 102
    nether:
        name: §6Nether Vending Machine
        model-data: 103
    sand:
        name: §6Sand Vending Machine
        model-data: 104
    prismarine:
        name: §6Prismarine Vending Machine
        model-data: 105
    ice:
        name: §6Ice Vending Machine
        model-data: 106
    blackstone:
        name: §6Blackstone Vending Machine
        model-data: 107
    copper:
        name: §6Copper Vending Machine
        model-data: 108
    amethyst:
        name: §6Amethyst Vending Machine
        model-data: 109

briefcase:
    wooden:
        name: §6Wooden Newt's Briefcase
        model-data: 201
    stone:
        name: §6Stone Newt's Briefcase
        model-data: 202
    nether:
        name: §6Nether Newt's Briefcase
        model-data: 203
    sand:
        name: §6Sand Newt's Briefcase
        model-data: 204
    prismarine:
        name: §6Prismarine Newt's Briefcase
        model-data: 205
    ice:
        name: §6Ice Newt's Briefcase
        model-data: 206
    blackstone:
        name: §6Blackstone Newt's Briefcase
        model-data: 207
    copper:
        name: §6Copper Newt's Briefcase
        model-data: 208
    amethyst:
        name: §6Amethyst Newt's Briefcase
        model-data: 209

############################################################
# +------------------------------------------------------+ #
# |                    Towny Settings                    | #
# +------------------------------------------------------+ #
#                                                          #
#   Ignore this section if you do not have Towny           #
#   installed.                                             #
#                                                          #
############################################################

# Use towny's build/destroy permissions for custom shop creation and removal?
towny-enabled: true
# Restrict shop creation and removal to shop plots? (Requires `towny-enabled` to be true)
only-shop-plots: false

############################################################
# +------------------------------------------------------+ #
# |                  WorldGuard Settings                 | #
# +------------------------------------------------------+ #
#                                                          #
#   Ignore this section if you do not have WorldGuard      #
#   installed.                                             #
#                                                          #
############################################################

# Use worldguard's build permissions for custom shop creation and removal?
worldguard-enabled: true

############################################################
# +------------------------------------------------------+ #
# |               GriefPrevention Settings               | #
# +------------------------------------------------------+ #
#                                                          #
#   Ignore this section if you do not have                 #
#   GriefPrevention installed.                             #
#                                                          #
############################################################

# Use griefprevention's build/break permissions for custom shop creation and removal?
griefprevention-enabled: true

############################################################
# +------------------------------------------------------+ #
# |                    Lands Settings                    | #
# +------------------------------------------------------+ #
#                                                          #
#   Ignore this section if you do not have Lands           #
#   installed.                                             #
#                                                          #
############################################################

# Use Lands's build/break permissions for custom shop creation and removal?
lands-enabled: true
